num_batch: 50
batch_size: 400
num_epochs: 300
use_pretrained_model: False
warmup_start: false
lr: 1e-4
split_sizes: 0.9
dataset_dirname: "dataset/"
checkpoint_filename: "checkpoints/checkpoint_18.pkl"
classes:
  [
    "Addidas",
    "Asus",
    "Auchan",
    "BMW",
    "Gucci",
    "Louis-vuitton",
    "Nike",
    "Phillips",
  ]
