num_batch: 50
batch_size: 300
num_epochs: 300
use_pretrained_model: False
warmup_start: false
lr: 0.005
split_sizes: 0.8
dataset_dirname: "dataset/"
checkpoint_filename: "checkpoints/checkpoint_500.pkl"